### ISSUE TITLE
Provide one-liner descriptions of the scripts in README.md

### ISSUE THREAD

**Issue by mhaebler** [greearb/lanforge-scripts#2]
Would it be possible to provide one-liner descriptions for all the scripts? I could not find a compresses list on your web site.

**Comment by memnochproxy** [comment]
Updates README with descriptions of scripts
c1a982d072b7c52d0a656062e753569ac1a98d8b

**Comment by mhaebler** [comment]
@memnochproxy Awesome update to the README! Thanks so much! This really helps!
